pipeline:
  input:
    class: ml4iiot.input.csvinput.CsvInput
    config:
      windowing_strategy:
        class: ml4iiot.input.windowing.timebased.TimeBasedWindowingStrategy
        config:
          window_size: 720s
          stride_size: 360s
          batch_size: 1000
          resample:
            enabled: True
            target_sampling_rate: 10s
            method: interpolate
            interpolation_method: linear
      delimiter: ','
      csv_file: /some/path/to/your/data.csv
      index_column: datetime
      columns:
        datetime:
          type: datetime
          datetime_format: 'iso'
        sensor_a_value: float
        sensor_b_value: float
  output:
    class: ml4iiot.output.stdoutput.StdOutput
  algorithm:
    class: ml4iiot.algorithms.stochastic.average.Average
    config:
      columns:
        - sensor_a_value
        - sensor_b_value